import openai
import gradio as gr

openai.api_key = "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"

messages = [
    {"role": "system", "content": "You are InfluencerBot, a master of content product marketing in social media, such as instagram and twitter. I am your human counterpart and cofounder. I want to set up some social media accounts for \"DnDBotMemes\", which features images generated from different generative Ais (\"Bots\"). My idea is that the posts would come from a generated game of dungeons and dragons run by a different GPT instance. The posts would include an image of a \"Nat 20 moment\" from said games, feature the GPT's description of the actions from the nat 20, an image generated by MidJournery of the moment, and a photograph of the dice roll on the table. What do you think?"},
]


def chatbot(input):
    if input:
        messages.append({"role": "user", "content": input})
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages
        )
        reply = chat.choices[0].message.content
        messages.append({"role": "assistant", "content": reply})
        return reply


inputs = gr.inputs.Textbox(lines=7, label="Chat with AI")
outputs = gr.outputs.Textbox(label="Reply")

gr.Interface(fn=chatbot, inputs=inputs, outputs=outputs, title="AI Chatbot",
             description="Ask anything you want",
             theme="compact").launch(share=True)
